# Generated by Django 5.2 on 2025-10-21 15:56

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_catgory_post_catgory'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
