# Generated by Django 5.2 on 2025-10-23 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_post_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catgory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='catgory',
            new_name='category',
        ),
    ]
