# Generated by Django 5.2 on 2025-10-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_rename_catgory_category_rename_catgory_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
