# Generated by Django 5.2 on 2025-10-31 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_remove_comment_published_date_comment_publishe_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='publishe_date',
            new_name='published_date',
        ),
    ]
