# Generated by Django 5.2 on 2025-11-01 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_rename_publishe_date_comment_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='published_date',
        ),
    ]
